name: scrcpy_buddy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  fluent_ui: ^4.13.0
  system_theme: ^3.1.2
  go_router: ^17.0.0
  flutter_acrylic: ^1.1.4
  flutter_i18n: ^0.36.3
  window_manager: ^0.5.1
  text_scroll: ^0.2.1

  # State
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  provider: ^6.1.5+1

  # Core
  process: ^5.0.4
  fpdart: ^1.1.1
  equatable: ^2.0.7
  reflectable: ^5.0.1
  file_selector: ^1.1.0

  # Storage
  streaming_shared_preferences: ^2.0.0
  objectbox: ^5.0.2
  objectbox_flutter_libs: ^5.0.2

  # Misc
  rxdart: ^0.28.0
  path: ^1.9.1
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  tray_manager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build: ^4.0.0

  test: ^1.25.15
  parameterized_test: ^2.0.1

  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  reflectable_builder:
    git: # Until https://github.com/google/reflectable.dart/pull/346 is merged and available
      url: https://github.com/sitespectrum/reflectable.dart
      ref: analyzer_8
      path: packages/reflectable_builder

  bloc_lint: ^0.3.3
  meta: ^1.16.0
  flutter_launcher_icons: ^0.14.4
  # Testing
  mockito: ^5.4.5
  objectbox_generator: ^5.0.2
  msix: any

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/i18n/
    - assets/tray/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_launcher_icons:
  image_path: "assets/icon_light.png"
  windows:
    generate: true
    icon_size: 256
  linux:
    generate: true
  macos:
    generate: true

msix_config:
  display_name: scrcpy buddy
  publisher_display_name: Codertainment
  publisher: CN=5EFFC3AA-14FC-4D47-AABD-2F91F482F2F7
  identity_name: Codertainment.scrcpybuddy
  store: true
  logo_path: assets/icon_light.png
  capabilities: privateNetworkClientServer, usb