name: Build Flutter Desktop Apps

on:
  push:
    branches: [ main ]

  pull_request:
    paths:
      - lib/**
      - linux/**
      - windows/**
      - macos/**
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Setup LXD
        uses: canonical/setup-lxd@v1

      - name: Install dependencies
        run: |
          # For FastForge
          sudo apt install locate
          wget -O appimagetool "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x appimagetool
          mv appimagetool /usr/local/bin/
          
          # For snap
          sudo snap install snapcraft --classic
          
          # install fastforge
          dart pub global activate fastforge
          
          # For tray_manager
          sudo apt-get install libayatana-appindicator3-dev

      - name: flutter pub get
        run: flutter pub get

      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build snap
        run: snapcraft pack --use-lxd

      - name: Upload snap
        uses: actions/upload-artifact@v4
        with:
          name: scrcpy_buddy_snap
          path: "*.snap"
          if-no-files-found: error

      - name: Build AppImage
        run: fastforge package --platform linux --targets appimage

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: scrcpy_buddy_appimage
          path: "dist/**/*.AppImage"
          if-no-files-found: error

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build Windows app
        run: flutter build windows --release

      - name: Create MSIX package
        run: dart run msix:create

      - name: Upload MSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: scrcpy_buddy_msix
          path: build\windows\x64\runner\Release\scrcpy_buddy.msix
          if-no-files-found: error

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install create-dmg
        run: npm install --global create-dmg

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build macOS app
        run: flutter build macos --release

      - name: Create DMG
        run: |
          create-dmg \
            'build/macos/Build/Products/Release/scrcpy buddy.app' \
            --no-code-sign \
            --no-version-in-filename

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: scrcpy_buddy_dmg
          path: 'scrcpy buddy.dmg'
          if-no-files-found: error
